"""This file is autogenerated according to HCA api spec. Don't modify."""
from ...added_command import AddedCommand

class GetBundles(AddedCommand):
    """Class containing info to reach the get endpoint of files."""

    @classmethod
    def _get_base_url(cls):
        return "https://hca-dss.czi.technology/v1"

    @classmethod
    def _get_endpoint_info(cls):
        return {'seen': False, 'body_params': {}, 'positional': [{'argument': 'uuid', 'required': True, 'required_for': ['/bundles/{uuid}'], 'description': 'Bundle unique ID.', 'type': 'string', 'format': None, 'pattern': '[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}'}], 'options': {'version': {'array': False, 'required': False, 'required_for': [], 'description': 'Timestamp of bundle creation in RFC3339.', 'type': 'string', 'format': 'date-time', 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['version']}, 'replica': {'array': False, 'required': False, 'required_for': [], 'description': 'Replica to fetch from.', 'type': 'string', 'format': None, 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['replica']}, 'directurls': {'array': False, 'required': False, 'required_for': [], 'description': 'Include direct-access URLs in the response.', 'type': 'boolean', 'format': None, 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['directurls']}}, 'requires_auth': False, 'description': 'Given a bundle UUID, return the latest version of that bundle.  If the version is provided, that version of the\nbundle is returned instead.\n'}
