"""This file is autogenerated according to HCA api spec. DON'T TOUCH!"""
from ...added_command import AddedCommand

class GetSearch(AddedCommand):
    """Class containing info to reach the get endpoint of files."""

    @classmethod
    def _get_base_url(cls):
        return "https://hca-dss.czi.technology/v1"

    @classmethod
    def get_command_name(cls):
        return "get-search"

    @classmethod
    def _get_endpoint_info(cls):
        return {'seen': False, 'body_params': {}, 'positional': [], 'options': {'query': {'array': False, 'required': True, 'required_for': ['/search'], 'description': 'Metadata query', 'type': 'string', 'format': None, 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['query']}}, 'description': 'Returns a list of bundles matching the given simple criteria\n'}
