"""This file is autogenerated according to HCA api spec. DON'T TOUCH!"""
from ...added_command import AddedCommand

class GetFiles(AddedCommand):
    """Class containing info to reach the get endpoint of files."""

    @classmethod
    def _get_base_url(cls):
        return "https://hca-dss.czi.technology/v1"

    @classmethod
    def get_command_name(cls):
        return "get-files"

    @classmethod
    def _get_endpoint_info(cls):
        return {'seen': True, 'body_params': {}, 'positional': [{'argument': 'uuid', 'required': False, 'required_for': ['/files/{uuid}'], 'description': 'A RFC4122-compliant ID for the file.', 'type': 'string', 'format': None, 'pattern': '[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}'}], 'options': {'replica': {'array': False, 'required': False, 'required_for': [], 'description': 'Replica to fetch from.', 'type': 'string', 'format': None, 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['replica']}, 'version': {'array': False, 'required': False, 'required_for': [], 'description': 'Timestamp of file creation in RFC3339.  If this is not provided, the latest version is returned.', 'type': 'string', 'format': 'date-time', 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['version']}}, 'description': 'Returns a list of files matching given criteria.\n'}
