"""This file is autogenerated according to HCA api spec. Don't modify."""
from ...added_command import AddedCommand

class PostSearch(AddedCommand):
    """Class containing info to reach the get endpoint of files."""

    @classmethod
    def _get_base_url(cls):
        return "https://hca-dss.czi.technology/v1"

    @classmethod
    def _get_endpoint_info(cls):
        return {u'description': u'Accepts Elasticsearch JSON query and returns matching bundle identifiers\n', u'body_params': {}, u'positional': [], u'seen': False, u'requires_auth': False, u'options': {}}
