"""This file is autogenerated according to HCA api spec. Don't modify."""
from ...added_command import AddedCommand

class PutSubscriptions(AddedCommand):
    """Class containing info to reach the get endpoint of files."""

    @classmethod
    def _get_base_url(cls):
        return "https://hca-dss.czi.technology/v1"

    @classmethod
    def _get_endpoint_info(cls):
        return {'seen': False, 'body_params': {'callback_url': {'description': 'Url to send request to when a bundle comes in that matches this query.', 'format': 'url', 'type': 'string', 'name': 'callback_url', 'req': True, 'in': 'body', 'array': False, 'hierarchy': ['callback_url']}, 'query': {'description': 'Elasticsearch query that will trigger the callback.', 'type': 'object', 'name': 'query', 'req': True, 'in': 'body', 'array': False, 'hierarchy': ['query']}}, 'positional': [], 'options': {'replica': {'array': False, 'required': True, 'required_for': ['/subscriptions'], 'description': 'Replica to write to. Can be one of aws, gcp, or azure.', 'type': 'string', 'format': None, 'pattern': None, 'metavar': None, 'in': 'query', 'hierarchy': ['replica']}, 'callback_url': {'array': False, 'required': True, 'required_for': ['/subscriptions'], 'description': 'Url to send request to when a bundle comes in that matches this query.', 'type': 'string', 'format': 'url', 'pattern': None, 'metavar': None, 'in': 'body', 'hierarchy': ['callback_url']}, 'query': {'array': False, 'required': True, 'required_for': ['/subscriptions'], 'description': 'Elasticsearch query that will trigger the callback.', 'type': 'object', 'format': None, 'pattern': None, 'metavar': None, 'in': 'body', 'hierarchy': ['query']}}, 'requires_auth': True, 'description': 'Create a new event subscription. Every time a new bundle version matches this query,\na request is sent to callback_url.\n'}
