#!/usr/bin/env python

from __future__ import absolute_import, division, print_function, unicode_literals

import logging

from hca.cli import CLI

logging.basicConfig(level=logging.ERROR)

CLI().run()
