#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import logging

logging.basicConfig(level=logging.ERROR)
logging.getLogger("botocore.vendored.requests").setLevel(logging.ERROR)

from hca import cli

cli.main()
