#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

from __future__ import absolute_import, division, print_function, unicode_literals

import os, sys, logging, pkgutil, importlib

logging.basicConfig(level=logging.ERROR)
logging.getLogger("botocore.vendored.requests").setLevel(logging.ERROR)

from hca import cli

cli.main()
